controller: 
  kind: DaemonSet
  
  reportNodeInternalIp: true

  hostPort:
    enabled: true
    ports:
      http: 80
      https: 443

  service:
    type: LoadBalancer
    externalIPs:
      - 192.168.49.2
    externalTrafficPolicy: Local